### ISSUE TITLE
python3 server.py时出错

### ISSUE THREAD

**Issue by justDoForever** [BithackTech/DeFiDefender#9]
![QQ截图20201203093907](https://user-images.githubusercontent.com/52912000/100952388-71067500-354b-11eb-9981-c428383f521a.png)
你能帮我解决一下吗，谢谢

**Comment by justDoForever** [comment]
graphy. PLease upgrade your Python.
Traceback (most recent call last):
File "server .py", line 4, in <module>
import re_ encryption
File "  reencryption client/re encryption.py", line 4, in <module>
from umbral import pre
File " /home/whc/ .Local/lib/python3. 5/site-packages/ umbral/pre.py", line 22，in <module>
from bytestring. splitter import BytestringSplitter
File "/home/whc/ .local/Lib/python3 .5/site-packages/bytestring splitter/__ init__ .py", line 76
raise AttributeError(f"{self.__ class__ } doesn't have a
{message_ name}, and it's not a partially split object either; those are {list(self . processed_ objects.k
eys())}")
| SyntaxError: invalid syntax
